---
title: "The Internet Of Things [ IoT ]"
author: "Wilber Wanjira"
date: '2016-05-10'
description: Three simple words that form an invisible yet supporting realm that coexists in the shadows of our dimension
slug: the-internet-of-things-iot
tags:
- internet of things
- iot
categories:
- iot
- internet of things
- writing
---

### Internet of Things
– a conjunction of three simple words that form an invisible yet supporting realm that coexists in the shadows of our dimension. If you have lived through the 80s and/or the 90s, you might have co-experienced the advent and “rise-to-power” of the internet. You might also be able to recall how you loved (or hated) to establish a dial-up internet connection over your telephone line and would shriek with sheer joy (if you got an acceptable connection rate) or despair (if your connection was as slow as snail mail).

In basic terminology, the internet is, at the moment, a network of networks. Each network and sub-network may house up to billions of devices. These devices may be intelligent or “dum-dum” dummies (which are not able to make decisions on their own). In early times (not the bronze or stone ages), there were few of dummy devices e.g. printers and online storage. Similarly, intelligent agents include computers (obviously) and handheld devices (like tablets and cellular devices).

But, as decades raced on, an exponential increase in interest and development of the internet was observed. This led to more people and their devices taking advantage of the internet’s connectivity. Countless man hours in libraries and research laboratories yielded new standards to improve the internet. Side-by-side, consumer devices were also developed to out-perform their predecessors and to cope up with the internet. All that ‘evolution’ is paying off and, even today, we can clearly see that almost every device near and around us is ‘on the net’. These devices range from washing machines and refrigerators to industrial control systems, from medical tests to equipment used in surgery, from our navigation devices to fleets of driverless vehicles.

But, what good would it do to put our appliances, systems and computers ‘on the net’? You see, as the internet and its ‘users’ increased, a new concept emerged – to control all our tasks remotely. That’s a dandy idea! Maybe, I’ll ask my refrigerator to order more milk if I ever run out of milk. And here’s the surprising part – my refrigerator can actually do that! In fact, my in-house entertainment system will automatically start playing my favorite ambience music at 6:00 AM in the morning while the coffee brewer prepares my cappuccino and the television switches to the morning warmup exercises. All I had to do was to apply my preferences, via my computer, to my house’s central system’s web profile. All these 6:00 AM activities are actually commands issued to my ‘house’ by the system’s web profile.

The concept and practice of pushing all our physical devices, for monitoring and sharing of data, onto the internet gave birth to the phenomenon of the Internet of Things. It’s not just about computers and their IT (information technology) related equipment anymore. It’s about controlling and regulating your life more proficiently and efficiently without actually interacting with the concerned devices physically. Whether you believe it or not, the earliest application of remote operation (via the internet) dates back to 1982, on the grounds of the Carnegie Mellon University where a modified Coke machine was able to report the number of drinks in its inventory. Not only does this phenomenon save time, it also opens up doors to opportunities and dreams-come-true.

It allows people with severe difficulties and disabilities to remotely interact and get along with their daily lives with minimal hiccups. It allows equipment, placed in harsh and dangerous environments, to be monitored and operated remotely (and by that I do not mean that you should be able to operate a rover on Mars from Earth). It allows medical implants to share their hosts’ diagnostics with the concerned doctors without any physical checkups. The possibilities are endless! And, like all advancements, the Internet of Things also has its fair share of disadvantages and critics.

Right off the bat, there is the issue of a privacy leak (according to some believers). A cold soda can sounds harmless, but the sharing of our preferences, activities and credentials over an unsecured and hack-able medium (the internet for this context) is more of a gamble than a risk. Data about every human being is already circulating on the internet and that can be attained by some ‘professionals’ without them breaking a sweat. People are already hesitant to put more of their precious data up for grabs.

Security concerns go hand-in-hand with privacy leakage. Not only the data circulating on the internet is tamper-able, the source devices of this data can also be manipulated. Such devices include car brakes, dashboard systems and even thermostats. All these devices have one thing in common – they have a connection to the internet (whether directly or passively). Perpetrators can control and reprogram these devices remotely and without you even noticing their despicable plans.

Lastly, and the most critical, is the loss of physical interaction for human beings. To some, this might seem to be an over-exaggeration at the moment. But, as things will progress, physical interactions WILL simmer down to just a few muscle movements. We already have smartphones that respond to voice commands (instead of their ancestral, button-laded counterparts). So, it’s not too hard to picture a future with excessively decreased physical interactions.

But, don’t let these turn you down because “when there is a WILL – there is a WAY”! We use motor vehicles everyday even though there are dangers of car accidents. We use cellular devices while accepting the hazards of being under the influence of radio waves. Yet, here we are and reading this article. There will always be challenges that hinder any advancement. And, once triumphed, there will be a new world on the other side!